belt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('login_manager.urls', namespace='login')),
    url(r'^travels/', include('trip_manager.urls', namespace='travel')),
]

login_manager/urls.py
"""Routes for managing user login and registration."""

from django.conf.urls import url
from .views import SignIn, logout_view


urlpatterns = [
    url(r'^$', SignIn.as_view(), name='signin'),
    url(r'^logout$', logout_view.as_view(), name='logout')
]

trip_manager/urls.py
"""Routes for managing user travel."""

from django.conf.urls import url
from .views import ListTrips, TripDetail, NewTrip, JoinTrip

urlpatterns = [
    url(r'^$', ListTrips.as_view(), name='list'),
    url(r'^destination/(?P<pk>[0-9]+)/$', TripDetail.as_view(), name='detail'),
    url(r'^add/$', NewTrip.as_view(), name='add'),
    url(r'^join/(?P<pk>[0-9]+)/$', JoinTrip.as_view(), name='join'),
]

belt/templates/belt/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Belt</title>
     {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'belt/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this bootstrap template -->
    <link href="{% static 'belt/css/heroic-features.css' %}" rel="stylesheet">
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Belt</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                <a class="nav-link" href="{% url 'login:signin' %}">Home
                    <span class="sr-only">(current)</span>
                </a>
                {% if user.is_authenticated %}
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'login:logout' %}">Logout</a>
                </li>
                {% else %}
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'login:signin' %}">Login</a>
                </li>
                {% endif %}
                {% comment %} <li class="nav-item">
                <a class="nav-link" href="{% url 'travel:list' %}">Trip Lists</a>
                </li> {% endcomment %}
            </ul>
            </div>
        </div>
    </nav>
    <!-- Page Content -->
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Website 2017</p>
        </div>
        <!-- /.container -->
    </footer>
    <!-- Bootstrap core JavaScript -->
    {% load static %}
    <script src="{% static 'belt/js/jquery.min.js' %}"></script>
    <script src="{% static 'belt/js/popper.min.js' %}"></script>
    <script src="{% static 'belt/js/bootstrap.min.js' %}"></script>
</body>
</html>