belt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^main/', include('login_manager.urls', namespace='login')),
    url(r'^travels/', include('trip_manager.urls', namespace='travel')),
]

trip_manager/urls.py
"""Routes for managing user travel."""

from django.conf.urls import url
from .views import ListTrips, TripDetail, NewTrip, JoinTrip

urlpatterns = [
    url(r'^$', ListTrips.as_view(), name='list'),
    url(r'^destination/(?P<pk>[0-9]+)/$', TripDetail.as_view(), name='detail'),
    url(r'^add/$', NewTrip.as_view(), name='add'),
    url(r'^join/(?P<pk>[0-9]+)/$', JoinTrip.as_view(), name='join'),
]

trip_manager/models.py
from django.db import models
from django.contrib.auth.models import User


class Trip(models.Model):
    planner = models.ForeignKey(
        User,
        related_name='trips',
    )
    guests = models.ManyToManyField(
        User,
        related_name='guest_trips',
        blank=True,
    )
    destination = models.CharField(max_length=150)
    description = models.CharField(max_length=150)
    date_from = models.DateField()
    date_to = models.DateField()

trip_manager/forms.py
"""Form for adding new trip."""

from django import forms
from django.contrib.auth.models import User
from .models import Trip
from django.forms.fields import DateField
from datetime import date


class NewTripForm(forms.ModelForm):
    date_from = forms.DateField(label='Travel Date From', widget=forms.SelectDateWidget)
    date_to = forms.DateField(label='Travel Date To', widget=forms.SelectDateWidget)

    class Meta:
        model = Trip
        fields = ['destination', 'description', 'date_from', 'date_to']


    def clean(self):
        cleaned_data = super(NewTripForm, self).clean()
        first_date = cleaned_data.get('date_from')
        second_date = cleaned_data.get('date_to')


        if second_date < first_date:
            raise forms.ValidationError('End date may not be before start date.')
        elif first_date < date.today():
            raise forms.ValidationError('Dates must not be in the past.')

trip_manager/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect, HttpResponse
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.views import View
from django.views.generic import DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Trip
from .forms import NewTripForm


class ListTrips(LoginRequiredMixin, View):
    login_required = True
    login_url = reverse_lazy('login:signin')

    def get(self, request):
        context = {
            'user_trips': [x for x in Trip.objects.filter(
                planner=self.request.user)] 
                + [x for x in Trip.objects.filter(guests=self.request.user)],
            'other_trips': [x for x in Trip.objects.exclude(
                planner=self.request.user).exclude(guests=self.request.user
                )],
            'person': self.request.user.first_name,
        }
        return render(request, 'trip_manager/index.html', context)


class TripDetail(LoginRequiredMixin, DetailView):
    login_required = True
    login_url = reverse_lazy('login:signin')
    model = Trip


class NewTrip(LoginRequiredMixin, CreateView):
    login_required = True
    login_url = reverse_lazy('login:signin')
    form_class = NewTripForm
    template_name = 'trip_manager/new_trip.html'
    success_url = reverse_lazy('travel:list')

    def form_valid(self, form):
        form.instance.planner = self.request.user
        return super(NewTrip, self).form_valid(form)


class JoinTrip(LoginRequiredMixin, View):
    login_required = True
    login_url = reverse_lazy('login:signin')
    def get(self, request, pk):
        trip = Trip.objects.get(id=pk)
        trip.guests.add(self.request.user)
        trip.save()
        # import pdb; pdb.set_trace()
        return redirect('travel:list')

trip_manager/templates/trip_manager/index.html
{% extends "belt/base.html" %}
{% block content %}
<h1>Hello, {{ person }}!</h1>
<br>
<p>Your Trip Schedules</p>
<table>
    <tr>
        <th>Destination</th>
        <th>Travel Start Date</th>
        <th>Travel End Date</th>
        <th>Plan</th>
    </tr>
    {% for trip in user_trips %}
    <tr>
        <td><a href="{% url 'travel:detail' pk=trip.id %}">{{ trip.destination }}</a></td>
        <td>{{ trip.date_from }}</td>
        <td>{{ trip.date_to }}</td>
        <td>{{ trip.description }}</td>
    </tr>
    {% endfor %}    
</table>
<br>
<p>Other User's Travel Plans</p>
<table>
    <tr>
        <th>Name</th>
        <th>Destination</th>
        <th>Travel Start Date</th>
        <th>Travel End Date</th>
        <th>Do You Want to Join?</th>
    </tr>
    {% for trip in other_trips %}
    <tr>
        <td>{{ trip.planner.name }}</td>
        <td><a href="{% url 'travel:detail' pk=trip.id %}">{{ trip.destination }}</a></td>
        <td>{{ trip.date_from }}</td>
        <td>{{ trip.date_to }}</td>
        <td><a href="{% url 'travel:join' pk=trip.id %}">Join</a></td>
    </tr>
    {% endfor %}
</table>
<a href="{% url 'travel:add' %}">Add Travel Plan</a>
{% endblock  %}

trip_manager/templates/trip_manager/new_trip.html
{% extends "belt/base.html" %}
{% block content %}
<h1>Add a Trip</h1>
    <form action="{% url 'travel:add' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Add">
    </form>
{% endblock  %}

trip_manager/templates/trip_manager/trip_detail.html
{% extends "belt/base.html" %}
{% block content %}
    <h1>{{ object.destination }}</h1>
    <p>Planned By: {{ object.planner }}</p>
    <p>Description: {{ object.description }}</p>
    <p>Travel Date From: {{ object.date_from }}</p>
    <p>Travel Date To: {{ object.date_to }}</p>
    <h1>Other users' joining the trip:</h1>
    <br>
    {% for user in object.guests.all %}
        <p>{{ user }}</p>
    {% endfor %}
{% endblock  %}